// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: devide.proto

package calculator

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DevidedByRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Number1 int64 `protobuf:"varint,1,opt,name=number1,proto3" json:"number1,omitempty"`
	Number2 int64 `protobuf:"varint,2,opt,name=number2,proto3" json:"number2,omitempty"`
}

func (x *DevidedByRequest) Reset() {
	*x = DevidedByRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_devide_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DevidedByRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DevidedByRequest) ProtoMessage() {}

func (x *DevidedByRequest) ProtoReflect() protoreflect.Message {
	mi := &file_devide_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DevidedByRequest.ProtoReflect.Descriptor instead.
func (*DevidedByRequest) Descriptor() ([]byte, []int) {
	return file_devide_proto_rawDescGZIP(), []int{0}
}

func (x *DevidedByRequest) GetNumber1() int64 {
	if x != nil {
		return x.Number1
	}
	return 0
}

func (x *DevidedByRequest) GetNumber2() int64 {
	if x != nil {
		return x.Number2
	}
	return 0
}

type DevidedByResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result int64 `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *DevidedByResponse) Reset() {
	*x = DevidedByResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_devide_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DevidedByResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DevidedByResponse) ProtoMessage() {}

func (x *DevidedByResponse) ProtoReflect() protoreflect.Message {
	mi := &file_devide_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DevidedByResponse.ProtoReflect.Descriptor instead.
func (*DevidedByResponse) Descriptor() ([]byte, []int) {
	return file_devide_proto_rawDescGZIP(), []int{1}
}

func (x *DevidedByResponse) GetResult() int64 {
	if x != nil {
		return x.Result
	}
	return 0
}

var File_devide_proto protoreflect.FileDescriptor

var file_devide_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x64, 0x65, 0x76, 0x69, 0x64, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a,
	0x63, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x22, 0x46, 0x0a, 0x10, 0x44, 0x65,
	0x76, 0x69, 0x64, 0x65, 0x64, 0x42, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18,
	0x0a, 0x07, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x31, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x07, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x31, 0x12, 0x18, 0x0a, 0x07, 0x6e, 0x75, 0x6d, 0x62,
	0x65, 0x72, 0x32, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x6e, 0x75, 0x6d, 0x62, 0x65,
	0x72, 0x32, 0x22, 0x2b, 0x0a, 0x11, 0x44, 0x65, 0x76, 0x69, 0x64, 0x65, 0x64, 0x42, 0x79, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x42,
	0x1f, 0x5a, 0x1d, 0x67, 0x6f, 0x2d, 0x67, 0x72, 0x70, 0x63, 0x2d, 0x73, 0x75, 0x6d, 0x2d, 0x6e,
	0x75, 0x6d, 0x62, 0x65, 0x72, 0x2f, 0x63, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_devide_proto_rawDescOnce sync.Once
	file_devide_proto_rawDescData = file_devide_proto_rawDesc
)

func file_devide_proto_rawDescGZIP() []byte {
	file_devide_proto_rawDescOnce.Do(func() {
		file_devide_proto_rawDescData = protoimpl.X.CompressGZIP(file_devide_proto_rawDescData)
	})
	return file_devide_proto_rawDescData
}

var file_devide_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_devide_proto_goTypes = []interface{}{
	(*DevidedByRequest)(nil),  // 0: calculator.DevidedByRequest
	(*DevidedByResponse)(nil), // 1: calculator.DevidedByResponse
}
var file_devide_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_devide_proto_init() }
func file_devide_proto_init() {
	if File_devide_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_devide_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DevidedByRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_devide_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DevidedByResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_devide_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_devide_proto_goTypes,
		DependencyIndexes: file_devide_proto_depIdxs,
		MessageInfos:      file_devide_proto_msgTypes,
	}.Build()
	File_devide_proto = out.File
	file_devide_proto_rawDesc = nil
	file_devide_proto_goTypes = nil
	file_devide_proto_depIdxs = nil
}
