// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: filter_same_number.proto

package calculator

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FilterSumNumberRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Number int32 `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
}

func (x *FilterSumNumberRequest) Reset() {
	*x = FilterSumNumberRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_filter_same_number_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FilterSumNumberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilterSumNumberRequest) ProtoMessage() {}

func (x *FilterSumNumberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_filter_same_number_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilterSumNumberRequest.ProtoReflect.Descriptor instead.
func (*FilterSumNumberRequest) Descriptor() ([]byte, []int) {
	return file_filter_same_number_proto_rawDescGZIP(), []int{0}
}

func (x *FilterSumNumberRequest) GetNumber() int32 {
	if x != nil {
		return x.Number
	}
	return 0
}

type FilterSumNumberResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Number int32 `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
}

func (x *FilterSumNumberResponse) Reset() {
	*x = FilterSumNumberResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_filter_same_number_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FilterSumNumberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilterSumNumberResponse) ProtoMessage() {}

func (x *FilterSumNumberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_filter_same_number_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilterSumNumberResponse.ProtoReflect.Descriptor instead.
func (*FilterSumNumberResponse) Descriptor() ([]byte, []int) {
	return file_filter_same_number_proto_rawDescGZIP(), []int{1}
}

func (x *FilterSumNumberResponse) GetNumber() int32 {
	if x != nil {
		return x.Number
	}
	return 0
}

var File_filter_same_number_proto protoreflect.FileDescriptor

var file_filter_same_number_proto_rawDesc = []byte{
	0x0a, 0x18, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x5f, 0x73, 0x61, 0x6d, 0x65, 0x5f, 0x6e, 0x75,
	0x6d, 0x62, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x63, 0x61, 0x6c, 0x63,
	0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x22, 0x30, 0x0a, 0x16, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72,
	0x53, 0x75, 0x6d, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x16, 0x0a, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x22, 0x31, 0x0a, 0x17, 0x46, 0x69, 0x6c, 0x74,
	0x65, 0x72, 0x53, 0x75, 0x6d, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x42, 0x1f, 0x5a, 0x1d, 0x67,
	0x6f, 0x2d, 0x67, 0x72, 0x70, 0x63, 0x2d, 0x73, 0x75, 0x6d, 0x2d, 0x6e, 0x75, 0x6d, 0x62, 0x65,
	0x72, 0x2f, 0x63, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_filter_same_number_proto_rawDescOnce sync.Once
	file_filter_same_number_proto_rawDescData = file_filter_same_number_proto_rawDesc
)

func file_filter_same_number_proto_rawDescGZIP() []byte {
	file_filter_same_number_proto_rawDescOnce.Do(func() {
		file_filter_same_number_proto_rawDescData = protoimpl.X.CompressGZIP(file_filter_same_number_proto_rawDescData)
	})
	return file_filter_same_number_proto_rawDescData
}

var file_filter_same_number_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_filter_same_number_proto_goTypes = []interface{}{
	(*FilterSumNumberRequest)(nil),  // 0: calculator.FilterSumNumberRequest
	(*FilterSumNumberResponse)(nil), // 1: calculator.FilterSumNumberResponse
}
var file_filter_same_number_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_filter_same_number_proto_init() }
func file_filter_same_number_proto_init() {
	if File_filter_same_number_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_filter_same_number_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FilterSumNumberRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_filter_same_number_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FilterSumNumberResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_filter_same_number_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_filter_same_number_proto_goTypes,
		DependencyIndexes: file_filter_same_number_proto_depIdxs,
		MessageInfos:      file_filter_same_number_proto_msgTypes,
	}.Build()
	File_filter_same_number_proto = out.File
	file_filter_same_number_proto_rawDesc = nil
	file_filter_same_number_proto_goTypes = nil
	file_filter_same_number_proto_depIdxs = nil
}
